# Generated by Django 6.0.4 on 2026-04-29 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='format',
            new_name='name',
        ),
    ]
